### PR TITLE
Validate json

### PR DESCRIPTION
**Pull request by lhuett**
Adding validate_json.py to validate changes to uploader.json 
and uploader.v2.json before merging.

### CODE REVIEW

**Comment by bfahr** [comment]
@SteveHNH This will need to be cherry-picked to the `uploaded_json` branch so that devs will be able to use it.

**Comment by lhuett** [comment]
@SteveHNH How do we test/play with this??

**Comment by SteveHNH** [comment]
@bfahr We made the assumption that Jenkins would be automating this check so some of the stuff in the current iteration of the script is meant for rthe way Jenkins does its git pulls and such. @lhuett you used this locally, right? I know we played with it a bit, but we had to jump through hoops some to get it to behave correctly.

Do we want to just throw it in master? We usually rebase uploader_json before release so it'll get the latest stuff in the next release. and jenkins won't do anything wiht it until we update the jenkinsfile, and I can test that in a separate branch

**Comment by lhuett** [comment]
@SteveHNH Yep, I tested it locally to be sure it still worked there.

**Comment by bfahr** [comment]
@SteveHNH @lhuett I wasn't sure how the CI works for this project, but if we can submit this against the uploader_json branch instead, and run this in the uploader_json branch CI for now that would check all the PRs which is what its targeted for.  You could run manually against the master for now as well right?

**Comment by lhuett** [comment]
@SteveHNH @bfahr I opened a new PR to there uploader_json branch that can replace his one...
[192, https://github.com/RedHatInsights/insights-core-assets/pull/192]

**Pull request closed without merging**
