### PR TITLE
RHEL8 - crypto policy for bind

### PR DESCRIPTION
**Pull request by jsvob**
related to https://github.com/RedHatInsights/insights-core/pull/1842

### CODE REVIEW

**Comment by jsvob** [comment]
https://projects.engineering.redhat.com/browse/INSPEC-191

**Comment by jsvob** [comment]
@bfahr Thank you for noticing it and sorry. I've made the branch branch off the `uploader_json` branch and changed to PR to have `uploader_json` as the base. I hope it is OK?

**Comment by jsvob** [comment]
@bfahr Hi, can you get it merged, please? :-)

**Comment by skontar** [comment]
@SteveHNH Can we get this merged before today release please?

**Comment by SteveHNH** [comment]
@skontar yes. We routinely go through these prior to release and merge them all in. It will get done.

**Comment by skontar** [comment]
@SteveHNH Awesome, thanks!

**Comment by jsvob** [comment]
@wcmitchell @SteveHNH @bfahr Thank you!

**Pull request merged**
