### PR TITLE
Add freeipa_healthcheck_log spec.

### PR DESCRIPTION
**Pull request by fcami**

### CODE REVIEW

**Comment by fcami** [comment]
hi @bfahr could you please tell me if the above was what you had in mind after we added the FreeIPA HealthCheck log parser to Insights-Core?

**Comment by fcami** [comment]
hi @lhuett 
Apologies for not picking up the alphabetic order earlier, I've fixed it, thanks!

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by fcami** [comment]
hi @lhuett do you need me to rebase?

**Comment by fcami** [comment]
Rebased. @lhuett please let me know if that's OK.

**Pull request merged**
