### PR TITLE
Specs for VirtlogdConf

### PR DESCRIPTION
**Pull request by psachin**
Parser: https://github.com/RedHatInsights/insights-core/pull/1539

Signed-off-by: Sachin Patil <psachin@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
Please create a JIRA Request for this spec change and resolve the conflicts in this PR.
https://projects.engineering.redhat.com/secure/RapidBoard.jspa?rapidView=2206

**Comment by psachin** [comment]
Specs: JIRA: https://projects.engineering.redhat.com/browse/INSPEC-121

**Comment by bfahr** [comment]
This PR is approved for merge, not sure why the test indicates failed, the job is missing.

**Comment by bfahr** [comment]
@psachin please fix the merge conflicts.

**Comment by bfahr** [comment]
This PR is approved for merge.

**Pull request merged**
