### PR TITLE
Specs for octavia.conf

### PR DESCRIPTION
**Pull request by bregman-arie**

### CODE REVIEW

**Comment by bfahr** [comment]
@bregman-arie you need to resubmit this PR against the uploader_json branch instead of the master branch.

**Comment by bfahr** [comment]
@bregman-arie this PR needs to be resubmitted against the `uploader_json` branch instead of the `master` branch.

**Comment by bregman-arie** [comment]
Done: https://github.com/RedHatInsights/insights-core-assets/pull/374

**Comment by bfahr** [comment]
Closing this request as it was replaced by #374

**Pull request closed without merging**
