### PR TITLE
spec ls_edac_mc

### PR DESCRIPTION
**Pull request by rasrivas-redhat**
Signed-off-by: Rahul Srivastava rasrivas@redhat.com

### CODE REVIEW

**Comment by lhuett** [comment]
@rasrivas-redhat Please re-submit the PR to the uploader_json branch

**Comment by rasrivas-redhat** [comment]
@lhuett - I have fixed the issue, please check

**Comment by rasrivas-redhat** [comment]
@lhuett - I have fixed the issue, can you please review it. Thanks.

**Comment by rasrivas-redhat** [comment]
@bfahr - please help to review the PR. Thanks.

**Pull request merged**
